version: '3.8'

services:
  pgdb:
    image: postgres:16
    container_name: pgdb
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: admin/
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork

  api-service:
    build:
      context: C:/Users/user/Desktop/ai-doctor-2/services/api
    container_name: api
    ports:
      - "8001:8001"
    env_file:
      - ./services/api/.env
    depends_on:
      - pgdb
    networks:
      - mynetwork

  ai-service:
    build:
      context: C:/Users/user/Desktop/ai-doctor-2/services/ai
    container_name: ai
    ports:
      - "8002:8002"
    env_file:
      - ./services/ai/.env
    depends_on:
      - pgdb
    networks:
      - mynetwork

  realtime-service:
    build:
      context: C:/Users/user/Desktop/ai-doctor-2/services/realtime
    container_name: realtime
    ports:
      - "8003:8003"
    env_file:
      - ./services/realtime/.env
    depends_on:
      - pgdb
    networks:
      - mynetwork



networks:
  mynetwork:
    driver: bridge

volumes:
  pgdata:
